
spring.datasource.url=jdbc:postgresql://localhost:5432/CanteenDb


spring.datasource.username=postgres


spring.datasource.password=Paras@123



spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Debug
logging.level.org.springframework.security=DEBUG

# JWT
jwt.secret=canteen-super-secret-key-must-be-at-least-32-chars
jwt.expiration=86400000

# Razorpay
razorpay.key.id=rzp_test_SaJERYJxlWnzZA
razorpay.key.secret=IsY3X1aNvjFtNxddBBzU7hn5
